name: Npm Run docker

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    

    
    # - name: setup docker
    #   run: |
    #     # Instal Docker
    #     sudo apt-get update
    #     sudo apt-get install -y docker.io

    #     # Jalankan Docker
    #     sudo systemctl start docker
    #     sudo systemctl enable docker

    #     # Periksa versi Docker
    #     docker --version


    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile.dev
          tags: gilbertsubay/docker-react:latest
          outputs: type=docker,dest=/tmp/docker-react.tar
    # - name: Menjalankan perintah build docker
    #   run: |
    #     docker build -t gilbertsubay/docker-react -f Dockerfile.dev .
    
    - name: Docker run
      run: |
        docker images
        docker run -e CI=true gilbertsubay/docker-react npm run test

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-react
        path: /tmp/docker-react.tar
    
  deploy:
    runs-on: ubuntu-latest

    needs: build


    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-react
        path: /tmp

    - name: Load Docker image
      run: docker load -i docker-react.tar 
    - name: Log in to AWS ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
        aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com

    - name: Docker image list
      run: |
        docker images
    - name: Tag Docker image
      run: docker tag gilbertsubay/docker-react ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/your-repo-name:latest
    
    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -r ${{ secrets.AWS_DEFAULT_REGION }} -p docker your-app-name
        eb deploy your-env-name --staged